["Priority: Critical"]
color = "e11d21"
name = "Priority: Critical"
description = ""

["Priority: High"]
color = "eb6420"
name = "Priority: High"
description = ""

["Priority: Low"]
color = "009800"
name = "Priority: Low"
description = "Synonym for On Hold"

["Priority: Medium"]
color = "fbca04"
name = "Priority: Medium"
description = ""

["Status: Abandoned"]
color = "000000"
name = "Status: Abandoned"
description = "Only for closed issues"

["Status: Accepted"]
color = "009800"
name = "Status: Accepted"
description = ""

["Status: Available"]
color = "bfe5bf"
name = "Status: Available"
description = ""

["Status: Blocked"]
color = "e11d21"
name = "Status: Blocked"
description = ""

["Status: Completed"]
color = "006b75"
name = "Status: Completed"
description = ""

["Status: Duplicate"]
color = "000000"
name = "Status: Duplicate"
description = ""

["Status: Help Wanted"]
color = "008672"
name = "Status: Help Wanted"
description = ""

["Status: In Progress"]
color = "cccccc"
name = "Status: In Progress"
description = ""

["Status: On Hold"]
color = "e11d21"
name = "Status: On Hold"
description = ""

["Status: Pending"]
color = "fef2c0"
name = "Status: Pending"
description = ""

["Status: Review Needed"]
color = "fbca04"
name = "Status: Review Needed"
description = ""

["Status: Revision Needed"]
color = "e11d21"
name = "Status: Revision Needed"
description = ""

["Status: Wont Fix"]
color = "ffffff"
name = "Status: Wont Fix"
description = ""

["Type: Bug"]
color = "e11d21"
name = "Type: Bug"
description = ""

["Type: Documentation"]
color = "0075ca"
name = "Type: Documentation"
description = ""

["Type: Enhancement"]
color = "84b6eb"
name = "Type: Enhancement"
description = ""

["Type: Maintenance"]
color = "fbca04"
name = "Type: Maintenance"
description = ""

["Type: Infrastructure"]
color = "fbca04"
name = "Type: Infrastructure"
description = ""

["Type: Playbook"]
color = "84db9b"
name = "Type: Playbook"
description = ""

["Type: Question"]
color = "cc317c"
name = "Type: Question"
description = ""

["Type: Course Development"]
color =  "#97adf4"
name = "Type: Course Development"
description = ""

["Type: Research"]
color =  "#3648aa"
name = "Type: Research"
description = ""

["Priority: Needs Triage"]
color =  "#000000"
name = "Priority: Needs Triage"
description = ""

["Type: Meta"]
color =  "#000000"
name = "Type: Meta"
description = "I award you no points. Links to other issues"

["Status: No Activity"]
color =  "#000000"
name = "Status: No Activity"
description = "Pre-abandoned, still open"

["Difficulty: 🟢"]
color =  "#333333"
name = "Difficulty: 🟢"
description = "Beginner"

["Difficulty: 🟦"]
color =  "#333333"
name = "Difficulty: 🟦"
description = "Intermediate"

["Difficulty: ♢"]
color =  "#333333"
name = "Difficulty: ♢"
description = "Expert"

["Difficulty: ♢♢"]
color =  "#333333"
name = "Difficulty: ♢♢"
description = "Expert Only"
